# Generated by Django 3.1.5 on 2021-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='detail',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
