# Generated by Django 3.1.5 on 2021-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
