# Generated by Django 3.1.5 on 2021-08-31 23:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
