# Generated by Django 3.1.5 on 2021-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0007_auto_20210831_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='qte',
        ),
        migrations.AddField(
            model_name='commande',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
