# Generated by Django 3.1.5 on 2021-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0008_auto_20210901_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panier',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
