# Generated by Django 3.1.5 on 2021-09-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0010_auto_20210902_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commanded',
            field=models.BooleanField(default=False),
        ),
    ]
