# Generated by Django 3.1.5 on 2022-02-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0011_commande_commanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Contacté'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='paied',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
