# Generated by Django 3.1.5 on 2022-02-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theo', '0012_auto_20220214_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
